# SPDX-FileCopyrightText: 2014-2026 The Beach Lab <https://beachlab.org>
# SPDX-License-Identifier: MIT
# Example only: a reversible fit-check variant.
# All omitted dimensions inherit from ../design.toml.

[drum]
axial_clearance = 1.5

[drum_enclosure]
side_clearance = 2.5
