; ALPHABETS_LICENSE_BEGIN
; SPDX-FileCopyrightText: 2014-2026 The Beach Lab <https://beachlab.org>
; SPDX-License-Identifier: MIT
; ALPHABETS_LICENSE_END
M48
; DRILL file KiCad 10.0.5 date 2026-08-18T14:54:11
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-08-18T14:54:11+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.5
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
METRIC
%
G90
G05
M30
