# SPDX-FileCopyrightText: 2014-2026 The Beach Lab <https://beachlab.org>
# SPDX-License-Identifier: MIT

VARIANT := definitive
FOLDER_SLUG := final
CARD_SIZE := 50x48
CHARACTER_PRESET := international-64
STICKER_SIZE := 45x91
include ../variant.mk
