; ALPHABETS_LICENSE_BEGIN
; SPDX-FileCopyrightText: 2014-2026 The Beach Lab <https://beachlab.org>
; SPDX-License-Identifier: MIT
; ALPHABETS_LICENSE_END
M48
; DRILL file KiCad 10.0.5 date 2026-08-19T04:56:44
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-08-19T04:56:44+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.5
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
%
G90
G05
M30
