# SPDX-FileCopyrightText: 2014-2026 The Beach Lab <https://beachlab.org>
# SPDX-License-Identifier: MIT

VARIANT := prototype
FOLDER_SLUG := prototype
CARD_SIZE := 55x43
CHARACTER_PRESET := demo-64
STICKER_SIZE := 50x80
include ../variant.mk
