# SPDX-FileCopyrightText: 2014-2026 The Beach Lab <https://beachlab.org>
# SPDX-License-Identifier: MIT

VARIANT := prototype
FOLDER_SLUG := prototype
CARD_SIZE := 55x43
CHARACTER_PRESET := demo-64
STICKER_SIZE := 50x80
REFERENCE_CAPTURE := $(V2_DIR)/Final/generated/blender/cards-position-capture.json
REFERENCE_SCENE := $(V2_DIR)/Final/generated/blender/scene.json
include ../variant.mk
